##Kyler Telge 1825829
print('Enter amount of lemon juice (in cups):')
lemons = float(input())
print('Enter amount of water (in cups):')
water = float(input())
print('Enter amount of agave nectar (in cups):')
nectar = float(input())
print('How many servings does this make?\n')
servings = float(input())
print('Lemonade ingredients - yields', '{:.2f}'.format(servings), 'servings')
print('{:.2f}'.format(lemons), 'cup(s) lemon juice')
print('{:.2f}'.format(water), 'cup(s) water')
print('{:.2f}'.format(nectar), 'cup(s) agave nectar\n')
print('How many servings would you like to make?')
user_num = float(input())
print('\nLemonade ingredients - yields', '{:.2f}'.format(user_num), 'servings')
print('{:.2f}'.format((1/3)*user_num), 'cup(s) lemon juice')
print('{:.2f}'.format((16/6)*user_num), 'cup(s) water')
print('{:.2f}'.format((2.5/6)*user_num), 'cup(s) agave nectar\n')
print('Lemonade ingredients - yields', '{:.2f}'.format(user_num), 'servings')
print('{:.2f}'.format(((1/3)*user_num)/16), 'gallon(s) lemon juice')
print('{:.2f}'.format(((16/6)*user_num)/16), 'gallon(s) water')
print('{:.2f}'.format(((2.5/6)*user_num)/16), 'gallon(s) agave nectar')